"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app

Reset folders:
    rm -rf build dist
"""

from setuptools import setup

APP = ['PDFMerger.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'bgicon.icns',
}

setup(
    app=APP,
    name="PDF Merger",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
